# Generated by Django 4.2.27 on 2026-02-03 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoBilletera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TOPUP', 'Recarga'), ('SPEND', 'Gasto'), ('REFUND', 'Reembolso'), ('ADJUST', 'Ajuste')], db_column='kind', max_length=16)),
                ('monto', models.IntegerField(db_column='amount', help_text='Positivo suma, negativo resta.')),
                ('tipo_referencia', models.CharField(db_column='reference_type', max_length=64)),
                ('id_referencia', models.CharField(db_column='reference_id', max_length=128)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('usuario', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_billetera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de billetera',
                'verbose_name_plural': 'Movimientos de billetera',
                'db_table': 'wallet_ledgerentry',
            },
        ),
        migrations.CreateModel(
            name='Billetera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.PositiveIntegerField(db_column='balance', default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('usuario', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='billetera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billetera',
                'verbose_name_plural': 'Billeteras',
                'db_table': 'wallet_wallet',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wallet.movimientobilletera',),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wallet.billetera',),
        ),
        migrations.AddIndex(
            model_name='movimientobilletera',
            index=models.Index(fields=['usuario', 'creado_en'], name='wallet_ledg_user_id_64c783_idx'),
        ),
    ]
