# Generated by Django 4.2.27 on 2026-02-04 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billetera',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='movimientobilletera',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='LedgerEntry',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TOPUP', 'Topup'), ('SPEND', 'Spend'), ('REFUND', 'Refund'), ('ADJUST', 'Adjust')], db_column='kind', max_length=16)),
                ('amount', models.IntegerField(db_column='amount')),
                ('reference_type', models.CharField(db_column='reference_type', max_length=64)),
                ('reference_id', models.CharField(db_column='reference_id', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'db_table': 'wallet_ledgerentry',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(db_column='balance', default=0)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'wallet_wallet',
            },
        ),
        migrations.DeleteModel(
            name='Billetera',
        ),
        migrations.DeleteModel(
            name='MovimientoBilletera',
        ),
        migrations.CreateModel(
            name='Billetera',
            fields=[
            ],
            options={
                'verbose_name': 'Billetera',
                'verbose_name_plural': 'Billeteras',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wallet.wallet',),
        ),
        migrations.CreateModel(
            name='MovimientoBilletera',
            fields=[
            ],
            options={
                'verbose_name': 'Movimiento de billetera',
                'verbose_name_plural': 'Movimientos de billetera',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wallet.ledgerentry',),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['user', 'created_at'], name='wallet_ledg_user_id_64c783_idx'),
        ),
    ]
