# Generated by Django 4.2.28 on 2026-02-09 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0002_remove_billetera_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('credits', models.PositiveIntegerField()),
                ('price_ars', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('mp_title', models.CharField(blank=True, default='', max_length=120)),
                ('mp_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Credit Pack',
                'verbose_name_plural': 'Credit Packs',
                'db_table': 'wallet_creditpack',
                'ordering': ['credits'],
            },
        ),
        migrations.CreateModel(
            name='WalletTopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('amount_ars', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credits', models.PositiveIntegerField()),
                ('mp_preference_id', models.CharField(blank=True, default='', max_length=120)),
                ('mp_payment_id', models.CharField(blank=True, default='', max_length=120)),
                ('checkout_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('pack', models.ForeignKey(db_column='pack_id', on_delete=django.db.models.deletion.PROTECT, related_name='topups', to='wallet.creditpack')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='wallet_topups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet Topup',
                'verbose_name_plural': 'Wallet Topups',
                'db_table': 'wallet_topup',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='wallet_topu_user_id_c136b5_idx'), models.Index(fields=['status'], name='wallet_topu_status_e6fae9_idx'), models.Index(fields=['mp_preference_id'], name='wallet_topu_mp_pref_78f4af_idx'), models.Index(fields=['mp_payment_id'], name='wallet_topu_mp_paym_6066b6_idx')],
            },
        ),
    ]
