# Generated by Django 4.2.27 on 2026-02-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Juego', 'verbose_name_plural': 'Catálogo de Juegos'},
        ),
        migrations.AlterModelOptions(
            name='gamesession',
            options={'verbose_name': 'Sesión de Juego', 'verbose_name_plural': 'Sesiones de Juego'},
        ),
        migrations.AddField(
            model_name='game',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='price_label',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='games', to='games_catalog.tag'),
        ),
    ]
