# Generated by Django 4.2.27 on 2026-02-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_catalog', '0003_alter_gamesession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='client_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
