# Generated by Django 4.2.27 on 2026-02-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_catalog', '0004_gamesession_client_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={'verbose_name': 'Sesión de juego', 'verbose_name_plural': 'Sesiones de juego'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Etiqueta', 'verbose_name_plural': 'Etiquetas'},
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('active', 'Activa'), ('finished', 'Finalizada'), ('error', 'Error')], default='active', max_length=16),
        ),
    ]
