# Generated by Django 4.2.27 on 2026-02-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_catalog', '0005_alter_gamesession_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games_catalog.tag',),
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Catálogo de Juegos',
                'ordering': ['-is_featured', 'name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games_catalog.game',),
        ),
        migrations.CreateModel(
            name='SesionJuego',
            fields=[
            ],
            options={
                'verbose_name': 'Sesión de juego',
                'verbose_name_plural': 'Sesiones de juego',
                'ordering': ['-started_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('games_catalog.gamesession',),
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-is_featured', 'name'], 'verbose_name': 'Juego', 'verbose_name_plural': 'Catálogo de Juegos'},
        ),
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['-started_at'], 'verbose_name': 'Sesión de juego', 'verbose_name_plural': 'Sesiones de juego'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='games_catalog_game_tags', related_name='games', to='games_catalog.tag'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('error', 'Error')], default='active', max_length=16),
        ),
        migrations.AlterModelTable(
            name='game',
            table='games_catalog_game',
        ),
        migrations.AlterModelTable(
            name='gamesession',
            table='games_catalog_gamesession',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='games_catalog_tag',
        ),
    ]
