# Generated by Django 4.2.27 on 2026-02-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_catalog', '0007_game_runner_url_gamesession_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='runner_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
