# Generated by Django 4.2.27 on 2026-02-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_catalog', '0008_gamesession_runner_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='runner_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
