# Generated by Django 4.2.27 on 2026-02-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triviareservation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_configs', to='clientes.company'),
        ),
    ]
