# Generated by Django 4.2.27 on 2026-02-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('trivia', '0002_alter_triviareservation_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='triviaconfig',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_config', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='triviareservation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_reservations', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='triviareservation',
            name='question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='trivia.questionset'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_set', 'is_active'], name='trivia_ques_questio_f2247c_idx'),
        ),
        migrations.AddIndex(
            model_name='questionset',
            index=models.Index(fields=['company', 'is_active'], name='trivia_ques_company_efc849_idx'),
        ),
        migrations.AddIndex(
            model_name='triviareservation',
            index=models.Index(fields=['company', 'starts_at'], name='trivia_triv_company_f21501_idx'),
        ),
        migrations.AddIndex(
            model_name='triviareservation',
            index=models.Index(fields=['status'], name='trivia_triv_status_9985cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='uq_choice_one_correct_per_question'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uq_questionset_company_name'),
        ),
    ]
