# Generated by Django 4.2.27 on 2026-02-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_question_is_active_alter_questionset_company_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='triviareservation',
            name='trivia_triv_company_f21501_idx',
        ),
        migrations.RemoveIndex(
            model_name='triviareservation',
            name='trivia_triv_status_9985cb_idx',
        ),
        migrations.AlterField(
            model_name='triviareservation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
