# Generated by Django 4.2.27 on 2026-02-05 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='HangmanWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('hint', models.CharField(blank=True, default='', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hangman_words', to='accounts.company')),
            ],
            options={
                'db_table': 'hangman_word',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'is_active'], name='hangman_wor_company_f790ce_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='hangmanword',
            constraint=models.UniqueConstraint(fields=('company', 'word'), name='uq_hangman_company_word'),
        ),
    ]
