# Generated by Django 4.2.27 on 2026-02-03 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_catalog', '0002_tag_alter_game_options_alter_gamesession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='gamesession',
            name='games_catal_user_id_9568f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='gamesession',
            name='games_catal_game_id_040336_idx',
        ),
        migrations.RenameField(
            model_name='gamesession',
            old_name='credits_spent',
            new_name='cost_charged',
        ),
        migrations.RenameField(
            model_name='gamesession',
            old_name='created_at',
            new_name='started_at',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games_catalog.game'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('error', 'Error')], default='active', max_length=16),
        ),
    ]
