# Generated by Django 4.2.27 on 2026-02-06 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
        ('games_catalog', '0009_alter_game_runner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='trivia.questionset'),
        ),
    ]
