# Generated by Django 4.2.28 on 2026-02-11 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games_catalog', '0010_gamesession_question_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo'), ('cancelado', 'Cancelado'), ('finalizado', 'Finalizado')], default='activo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='games_catalog.game')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_juego', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'games_catalog_contratojuego',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario', 'juego', 'estado'], name='games_catal_usuario_412223_idx'), models.Index(fields=['fecha_inicio', 'fecha_fin'], name='games_catal_fecha_i_c19e03_idx')],
            },
        ),
    ]
