# Generated by Django 4.2.28 on 2026-02-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games_catalog", "0011_contratojuego"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameCustomization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config", models.JSONField(blank=True, default=dict)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customization",
                        to="games_catalog.contratojuego",
                    ),
                ),
            ],
            options={
                "db_table": "games_catalog_gamecustomization",
                "ordering": ["-actualizado_en"],
            },
        ),
    ]
