# Generated by Django 6.0.2 on 2026-02-12 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_catalog', '0012_gamecustomization'),
        ('trivia', '0004_remove_triviareservation_trivia_triv_company_f21501_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratojuego',
            name='trivia_question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_juego', to='trivia.questionset'),
        ),
    ]
