# Generated by Django 4.2.28 on 2026-02-12 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_catalog', '0013_contratojuego_trivia_question_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoJuegoFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_evento', to='games_catalog.contratojuego')),
            ],
            options={
                'db_table': 'games_catalog_contratojuegofecha',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['fecha'], name='games_catal_fecha_239215_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contratojuegofecha',
            constraint=models.UniqueConstraint(fields=('contrato', 'fecha'), name='games_catalog_unique_contract_event_date'),
        ),
    ]
